version: '3.8'
services:
  reactapp:
    build: ./react-app
    container_name: react_c
    ports:
      - '3000:3000'
    volumes:
      - ./react-app/app
      - ./react-app/node_modules
    stdin_open: true
    tty: true